package server
import("encoding/json";"errors";"fmt";"io";"log";"mime";"net/http";"strings";"sync";"time";"github.com/Ploos-AS/BotWeb/internal/pbmp";"github.com/Ploos-AS/BotWeb/internal/registry")
type metricsState struct{mu sync.Mutex;pbmpOK uint64;pbmpError uint64;pbmpNanos uint64;readyChecked int;readyReachable int;loginThrottled uint64}
func(m *metricsState)observe(ok bool,d time.Duration){m.mu.Lock();defer m.mu.Unlock();if ok{m.pbmpOK++}else{m.pbmpError++};m.pbmpNanos+=uint64(d)}
type Server struct{r registry.Registry;auth AuthConfig;sessions *sessionStore;metrics *metricsState;loginMu sync.Mutex;loginFailures []time.Time}
func New(path string)(*Server,error){return NewWithAuth(path,AuthConfig{})}
func NewWithAuth(path string,auth AuthConfig)(*Server,error){r,e:=registry.Load(path);return &Server{r:r,auth:auth,sessions:newSessionStore(),metrics:&metricsState{}},e}
func(s *Server)Handler()http.Handler{m:=http.NewServeMux();m.HandleFunc("GET /",s.index);m.HandleFunc("GET /login",s.loginPage);m.HandleFunc("POST /login",s.login);m.HandleFunc("POST /logout",s.logout);m.HandleFunc("GET /app.css",assetCSS);m.HandleFunc("GET /api/v1/session",s.sessionInfo);m.HandleFunc("POST /api/v1/session/rotate",s.rotateSession);m.HandleFunc("GET /app.js",assetJS);m.HandleFunc("GET /metrics",s.metricsHandler);m.HandleFunc("GET /readyz",s.readyz);m.HandleFunc("GET /healthz",func(w http.ResponseWriter,_ *http.Request){w.Header().Set("Content-Type","application/json");w.Write([]byte("{\"ok\":true}\n"))});m.HandleFunc("GET /api/v1/bots",s.bots);m.HandleFunc("GET /api/v1/bots/",s.bot);m.HandleFunc("POST /api/v1/bots/",s.botAction);return securityHeaders(authMiddleware(s.auth,s.sessions,m))}
func securityHeaders(next http.Handler)http.Handler{return http.HandlerFunc(func(w http.ResponseWriter,r *http.Request){if strings.HasPrefix(r.URL.Path,"/api/"){w.Header().Set("Cache-Control","no-store")};w.Header().Set("X-Content-Type-Options","nosniff");w.Header().Set("X-Frame-Options","DENY");w.Header().Set("Referrer-Policy","no-referrer");w.Header().Set("Content-Security-Policy","default-src 'self'; script-src 'self'; style-src 'self'; connect-src 'self'; img-src 'self'; base-uri 'none'; frame-ancestors 'none'; form-action 'self'");next.ServeHTTP(w,r)})}
func(s *Server)index(w http.ResponseWriter,r *http.Request){if r.URL.Path!="/"&&!strings.HasPrefix(r.URL.Path,"/bots/"){http.NotFound(w,r);return};w.Header().Set("Content-Type","text/html; charset=utf-8");w.Write([]byte(indexHTML))}
func(s *Server)bots(w http.ResponseWriter,_ *http.Request){type safe struct{ID string `json:"id"`;Name string `json:"name"`;Transport string `json:"transport"`};v:=make([]safe,0,len(s.r.Bots));for _,b:=range s.r.Bots{v=append(v,safe{b.ID,b.Name,b.Transport})};write(w,v)}
func(s *Server)bot(w http.ResponseWriter,r *http.Request){p:=strings.TrimPrefix(r.URL.Path,"/api/v1/bots/");parts:=strings.Split(strings.Trim(p,"/"),"/");if len(parts)!=2{http.NotFound(w,r);return};b,ok:=s.r.Find(parts[0]);if !ok||b.Transport!="unix"{http.NotFound(w,r);return};methods:=map[string]string{"info":"bot.info","capabilities":"capabilities.list","networks":"networks.list","protocol":"pbmp.info","channels":"channels.list","modules":"modules.list","metrics":"metrics.read","botai":"botai.status","logs":"logs.read","config":"config.read","config-schema":"config.schema"};method,ok:=methods[parts[1]];if !ok{http.NotFound(w,r);return};v,e:=s.pbmpCall(b.Endpoint,method,nil);if e!=nil{http.Error(w,e.Error(),http.StatusBadGateway);return};w.Header().Set("Content-Type","application/json");w.Write(v);w.Write([]byte("\n"))}
func validOrigin(c AuthConfig,r *http.Request)bool{if o:=r.Header.Get("Origin");o!=""{scheme:="http";if requestHTTPS(c,r){scheme="https"};return o==scheme+"://"+r.Host};return true}
func hasMediaType(r *http.Request,want string)bool{mt,_,e:=mime.ParseMediaType(r.Header.Get("Content-Type"));return e==nil&&mt==want}
func validWriteRequest(c AuthConfig,r *http.Request)bool{if !hasMediaType(r,"application/json"){return false};return validOrigin(c,r)}
type auditEvent struct{Schema string `json:"schema"`;Event string `json:"event"`;Bot string `json:"bot,omitempty"`;Result string `json:"result"`;Auth string `json:"auth,omitempty"`;Role string `json:"role,omitempty"`}
func audit(r *http.Request,event,bot,result string){v:=auditEvent{Schema:"botweb.audit.v1",Event:event,Bot:bot,Result:result,Auth:authenticatedMethod(r),Role:authenticatedRole(r)};b,e:=json.Marshal(v);if e!=nil{return};log.Print(string(b))}
func auditManagement(r *http.Request,event,bot,result string){audit(r,event,bot,result)}
func(s *Server)botAction(w http.ResponseWriter,r *http.Request){if !validWriteRequest(s.auth,r){http.Error(w,"invalid write request",http.StatusForbidden);return};p:=strings.TrimPrefix(r.URL.Path,"/api/v1/bots/");parts:=strings.Split(strings.Trim(p,"/"),"/");if len(parts)!=3{http.NotFound(w,r);return}; if parts[1]=="modules"&&(parts[2]=="reload"||parts[2]=="enable"||parts[2]=="disable"){b,ok:=s.r.Find(parts[0]);if !ok||b.Transport!="unix"{http.NotFound(w,r);return};var q struct{ID string `json:"id"`};if e:=decodeJSONBody(w,r,&q);e!=nil{writeJSONDecodeError(w,e);return};if q.ID==""{http.Error(w,"invalid request",http.StatusBadRequest);return};v,e:=s.pbmpCall(b.Endpoint,"modules."+parts[2],map[string]any{"id":q.ID});if e!=nil{auditManagement(r,"modules."+parts[2],parts[0],"error");http.Error(w,e.Error(),http.StatusBadGateway);return};auditManagement(r,"modules."+parts[2],parts[0],"ok");w.Header().Set("Content-Type","application/json");w.Write(v);w.Write([]byte("\n"));return}; if parts[1]!="channels"||(parts[2]!="join"&&parts[2]!="part"){http.NotFound(w,r);return};b,ok:=s.r.Find(parts[0]);if !ok||b.Transport!="unix"{http.NotFound(w,r);return};var q struct{Network string `json:"network"`;Name string `json:"name"`;Reason string `json:"reason"`};if e:=decodeJSONBody(w,r,&q);e!=nil{writeJSONDecodeError(w,e);return};method:="channels."+parts[2];v,e:=s.pbmpCall(b.Endpoint,method,map[string]any{"network":q.Network,"name":q.Name,"reason":q.Reason});if e!=nil{auditManagement(r,method,parts[0],"error");http.Error(w,e.Error(),http.StatusBadGateway);return};auditManagement(r,method,parts[0],"ok");w.Header().Set("Content-Type","application/json");w.Write(v);w.Write([]byte("\n"))}
func decodeJSONBody(w http.ResponseWriter,r *http.Request,v any)error{d:=json.NewDecoder(http.MaxBytesReader(w,r.Body,4096));d.DisallowUnknownFields();if e:=d.Decode(v);e!=nil{return e};var extra any;if e:=d.Decode(&extra);e!=io.EOF{return fmt.Errorf("request must contain one JSON value")};return nil}
func writeJSONDecodeError(w http.ResponseWriter,e error){var max *http.MaxBytesError;if errors.As(e,&max){http.Error(w,"request too large",http.StatusRequestEntityTooLarge);return};http.Error(w,"invalid request",http.StatusBadRequest)}
func write(w http.ResponseWriter,v any){w.Header().Set("Content-Type","application/json");json.NewEncoder(w).Encode(v)}

func(s *Server)loginPage(w http.ResponseWriter,r *http.Request){w.Header().Set("Cache-Control","no-store");if !s.auth.enabled(){http.Redirect(w,r,"/",http.StatusSeeOther);return};w.Header().Set("Content-Type","text/html; charset=utf-8");w.Write([]byte(loginHTML))}
func(s *Server)login(w http.ResponseWriter,r *http.Request){w.Header().Set("Cache-Control","no-store");if !s.auth.enabled(){http.NotFound(w,r);return};if !validOrigin(s.auth,r){http.Error(w,"invalid origin",http.StatusForbidden);return};if !hasMediaType(r,"application/x-www-form-urlencoded"){http.Error(w,"unsupported content type",http.StatusUnsupportedMediaType);return};r.Body=http.MaxBytesReader(w,r.Body,4096);if e:=r.ParseForm();e!=nil{if _,ok:=e.(*http.MaxBytesError);ok{http.Error(w,"request too large",http.StatusRequestEntityTooLarge);return};http.Error(w,"invalid request",http.StatusBadRequest);return};role:=s.auth.role(r.PostFormValue("token"));if role==""{if !s.loginAllowed(){s.metrics.mu.Lock();s.metrics.loginThrottled++;s.metrics.mu.Unlock();w.Header().Set("Retry-After","60");http.Error(w,"too many login attempts",http.StatusTooManyRequests);return};s.recordLoginFailure();http.Error(w,"invalid credentials",http.StatusUnauthorized);return};s.clearLoginFailures();if ck,e:=r.Cookie("botweb_session");e==nil{s.sessions.delete(ck.Value)};id,e:=s.sessions.create(role);if e!=nil{http.Error(w,"session unavailable",http.StatusInternalServerError);return};http.SetCookie(w,&http.Cookie{Name:"botweb_session",Value:id,Path:"/",HttpOnly:true,Secure:requestHTTPS(s.auth,r),SameSite:http.SameSiteStrictMode,MaxAge:43200});http.Redirect(w,r,"/",http.StatusSeeOther)}
func(s *Server)logout(w http.ResponseWriter,r *http.Request){w.Header().Set("Cache-Control","no-store");if ck,e:=r.Cookie("botweb_session");e==nil{s.sessions.delete(ck.Value);audit(r,"session.logout","","ok")};http.SetCookie(w,&http.Cookie{Name:"botweb_session",Value:"",Path:"/",HttpOnly:true,Secure:requestHTTPS(s.auth,r),SameSite:http.SameSiteStrictMode,MaxAge:-1});http.Redirect(w,r,"/login",http.StatusSeeOther)}

func(s *Server)sessionInfo(w http.ResponseWriter,r *http.Request){w.Header().Set("Cache-Control","no-store");role:=requestRole(s.auth,s.sessions,r);out:=map[string]any{"authenticated":role!="","role":role};if ck,e:=r.Cookie("botweb_session");e==nil{if v,ok:=s.sessions.get(ck.Value);ok{out["created_at"]=v.created.UTC();out["expires_at"]=v.expires.UTC();out["csrf_token"]=v.csrf}};write(w,out)}
func(s *Server)rotateSession(w http.ResponseWriter,r *http.Request){w.Header().Set("Cache-Control","no-store");ck,e:=r.Cookie("botweb_session");if e!=nil{http.Error(w,"session required",http.StatusBadRequest);return};id,e:=s.sessions.rotate(ck.Value);if e!=nil{http.Error(w,"session unavailable",http.StatusUnauthorized);return};http.SetCookie(w,&http.Cookie{Name:"botweb_session",Value:id,Path:"/",HttpOnly:true,Secure:requestHTTPS(s.auth,r),SameSite:http.SameSiteStrictMode,MaxAge:43200});audit(r,"session.rotate","","ok");w.WriteHeader(http.StatusNoContent)}

func(s *Server)metricsHandler(w http.ResponseWriter,_ *http.Request){s.metrics.mu.Lock();ok,fail,nanos,checked,reachable,throttled:=s.metrics.pbmpOK,s.metrics.pbmpError,s.metrics.pbmpNanos,s.metrics.readyChecked,s.metrics.readyReachable,s.metrics.loginThrottled;s.metrics.mu.Unlock();w.Header().Set("Content-Type","text/plain; version=0.0.4");fmt.Fprintf(w,"# HELP botweb_registry_bots Number of configured bots.\n# TYPE botweb_registry_bots gauge\nbotweb_registry_bots %d\n",len(s.r.Bots));fmt.Fprintf(w,"# HELP botweb_pbmp_requests_total PBMP requests by result.\n# TYPE botweb_pbmp_requests_total counter\nbotweb_pbmp_requests_total{result=\"ok\"} %d\nbotweb_pbmp_requests_total{result=\"error\"} %d\n",ok,fail);fmt.Fprintf(w,"# HELP botweb_pbmp_request_duration_seconds_sum Total PBMP request duration.\n# TYPE botweb_pbmp_request_duration_seconds_sum counter\nbotweb_pbmp_request_duration_seconds_sum %.6f\n",float64(nanos)/1e9);fmt.Fprintf(w,"# HELP botweb_bots_checked Number of bots checked by the latest readiness probe.\n# TYPE botweb_bots_checked gauge\nbotweb_bots_checked %d\n# HELP botweb_bots_reachable Number of bots reachable in the latest readiness probe.\n# TYPE botweb_bots_reachable gauge\nbotweb_bots_reachable %d\n",checked,reachable);fmt.Fprintf(w,"# HELP botweb_login_throttled_total Login attempts rejected by the global failure limiter.\n# TYPE botweb_login_throttled_total counter\nbotweb_login_throttled_total %d\n",throttled)}
func(s *Server)pbmpCall(endpoint,method string,params map[string]any)(json.RawMessage,error){start:=time.Now();var v json.RawMessage;var e error;if params==nil{v,e=(pbmp.Client{Endpoint:endpoint}).Call(method)}else{v,e=(pbmp.Client{Endpoint:endpoint}).CallParams(method,params)};s.metrics.observe(e==nil,time.Since(start));return v,e}

func probeReachability(endpoints []string,probe func(string)bool)int{results:=make(chan bool,len(endpoints));for _,endpoint:=range endpoints{go func(ep string){results<-probe(ep)}(endpoint)};reachable:=0;for range endpoints{if <-results{reachable++}};return reachable}

const runtimeReadinessMethod="pbmp.info"

func(s *Server)readyz(w http.ResponseWriter,_ *http.Request){if len(s.r.Bots)==0{write(w,map[string]any{"ok":true,"configured":0,"reachable":0});return};endpoints:=make([]string,0,len(s.r.Bots));for _,b:=range s.r.Bots{if b.Transport=="unix"{endpoints=append(endpoints,b.Endpoint)}};checked:=len(endpoints);if checked==0{w.WriteHeader(http.StatusServiceUnavailable);write(w,map[string]any{"ok":false,"configured":len(s.r.Bots),"checked":0,"reachable":0});return};reachable:=probeReachability(endpoints,func(endpoint string)bool{_,e:=s.pbmpCall(endpoint,runtimeReadinessMethod,nil);return e==nil});s.metrics.mu.Lock();s.metrics.readyChecked=checked;s.metrics.readyReachable=reachable;s.metrics.mu.Unlock();if reachable==0{w.WriteHeader(http.StatusServiceUnavailable)};write(w,map[string]any{"ok":reachable>0,"configured":len(s.r.Bots),"checked":checked,"reachable":reachable})}

func(s *Server)loginAllowed()bool{s.loginMu.Lock();defer s.loginMu.Unlock();now:=time.Now();cut:=now.Add(-time.Minute);kept:=s.loginFailures[:0];for _,v:=range s.loginFailures{if v.After(cut){kept=append(kept,v)}};s.loginFailures=kept;return len(kept)<10}
func(s *Server)recordLoginFailure(){s.loginMu.Lock();defer s.loginMu.Unlock();s.loginFailures=append(s.loginFailures,time.Now());if len(s.loginFailures)>10{s.loginFailures=s.loginFailures[len(s.loginFailures)-10:]}}
func(s *Server)clearLoginFailures(){s.loginMu.Lock();s.loginFailures=nil;s.loginMu.Unlock()}
