package server
import("encoding/json";"net/http";"strings";"github.com/Ploos-AS/BotWeb/internal/pbmp";"github.com/Ploos-AS/BotWeb/internal/registry")
type Server struct{r registry.Registry}
func New(path string)(*Server,error){r,e:=registry.Load(path);return &Server{r:r},e}
func(s *Server)Handler()http.Handler{m:=http.NewServeMux();m.HandleFunc("GET /",s.index);m.HandleFunc("GET /app.css",assetCSS);m.HandleFunc("GET /app.js",assetJS);m.HandleFunc("GET /healthz",func(w http.ResponseWriter,_ *http.Request){w.Header().Set("Content-Type","application/json");w.Write([]byte("{\"ok\":true}\n"))});m.HandleFunc("GET /api/v1/bots",s.bots);m.HandleFunc("GET /api/v1/bots/",s.bot);m.HandleFunc("POST /api/v1/bots/",s.botAction);return securityHeaders(m)}
func securityHeaders(next http.Handler)http.Handler{return http.HandlerFunc(func(w http.ResponseWriter,r *http.Request){w.Header().Set("X-Content-Type-Options","nosniff");w.Header().Set("X-Frame-Options","DENY");w.Header().Set("Referrer-Policy","no-referrer");w.Header().Set("Content-Security-Policy","default-src 'self'; script-src 'self'; style-src 'self'; connect-src 'self'; img-src 'self'; base-uri 'none'; frame-ancestors 'none'");next.ServeHTTP(w,r)})}
func(s *Server)index(w http.ResponseWriter,r *http.Request){if r.URL.Path!="/"&&!strings.HasPrefix(r.URL.Path,"/bots/"){http.NotFound(w,r);return};w.Header().Set("Content-Type","text/html; charset=utf-8");w.Write([]byte(indexHTML))}
func(s *Server)bots(w http.ResponseWriter,_ *http.Request){type safe struct{ID string `json:"id"`;Name string `json:"name"`;Transport string `json:"transport"`};v:=make([]safe,0,len(s.r.Bots));for _,b:=range s.r.Bots{v=append(v,safe{b.ID,b.Name,b.Transport})};write(w,v)}
func(s *Server)bot(w http.ResponseWriter,r *http.Request){p:=strings.TrimPrefix(r.URL.Path,"/api/v1/bots/");parts:=strings.Split(strings.Trim(p,"/"),"/");if len(parts)!=2{http.NotFound(w,r);return};b,ok:=s.r.Find(parts[0]);if !ok||b.Transport!="unix"{http.NotFound(w,r);return};methods:=map[string]string{"info":"bot.info","capabilities":"capabilities.list","networks":"networks.list","protocol":"pbmp.info","channels":"channels.list","modules":"modules.list"};method,ok:=methods[parts[1]];if !ok{http.NotFound(w,r);return};v,e:=(pbmp.Client{Endpoint:b.Endpoint}).Call(method);if e!=nil{http.Error(w,e.Error(),http.StatusBadGateway);return};w.Header().Set("Content-Type","application/json");w.Write(v);w.Write([]byte("\n"))}
func(s *Server)botAction(w http.ResponseWriter,r *http.Request){p:=strings.TrimPrefix(r.URL.Path,"/api/v1/bots/");parts:=strings.Split(strings.Trim(p,"/"),"/");if len(parts)!=3||parts[1]!="channels"||(parts[2]!="join"&&parts[2]!="part"){http.NotFound(w,r);return};b,ok:=s.r.Find(parts[0]);if !ok||b.Transport!="unix"{http.NotFound(w,r);return};var q struct{Network string `json:"network"`;Name string `json:"name"`;Reason string `json:"reason"`};if json.NewDecoder(http.MaxBytesReader(w,r.Body,4096)).Decode(&q)!=nil{http.Error(w,"invalid request",400);return};method:="channels."+parts[2];v,e:=(pbmp.Client{Endpoint:b.Endpoint}).CallParams(method,map[string]any{"network":q.Network,"name":q.Name,"reason":q.Reason});if e!=nil{http.Error(w,e.Error(),http.StatusBadGateway);return};w.Header().Set("Content-Type","application/json");w.Write(v);w.Write([]byte("\n"))}
func write(w http.ResponseWriter,v any){w.Header().Set("Content-Type","application/json");json.NewEncoder(w).Encode(v)}
