package server
import("encoding/json";"time";"os";"path/filepath";"net/http";"net/http/httptest";"strings";"testing")
func testServer(t *testing.T)*Server{t.Helper();p:=filepath.Join(t.TempDir(),"bots.json");if err:=os.WriteFile(p,[]byte(`{"bots":[{"id":"x","name":"Example","transport":"unix","endpoint":"/secret/path.sock"}]}`),0600);err!=nil{t.Fatal(err)};s,e:=New(p);if e!=nil{t.Fatal(e)};return s}
func TestIndexAndHeaders(t *testing.T){r:=httptest.NewRequest("GET","/",nil);w:=httptest.NewRecorder();testServer(t).Handler().ServeHTTP(w,r);if w.Code!=200{t.Fatal(w.Code)};if !strings.Contains(w.Body.String(),"PBMP fleet console"){t.Fatal("missing UI")};if w.Header().Get("Content-Security-Policy")==""{t.Fatal("missing CSP")}}
func TestRegistryDoesNotLeakEndpoint(t *testing.T){r:=httptest.NewRequest("GET","/api/v1/bots",nil);w:=httptest.NewRecorder();testServer(t).Handler().ServeHTTP(w,r);if strings.Contains(w.Body.String(),"secret/path"){t.Fatal("endpoint leaked")}}

func TestBotRouteServesAppShell(t *testing.T){r:=httptest.NewRequest("GET","/bots/x",nil);w:=httptest.NewRecorder();testServer(t).Handler().ServeHTTP(w,r);if w.Code!=200{t.Fatal(w.Code)};if !strings.Contains(w.Body.String(),"PBMP fleet console"){t.Fatal("missing app shell")}}
func TestCapabilityNavigationIsGeneric(t *testing.T){r:=httptest.NewRequest("GET","/app.js",nil);w:=httptest.NewRecorder();testServer(t).Handler().ServeHTTP(w,r);body:=w.Body.String();if !strings.Contains(body,"channels.list")||!strings.Contains(body,"modules.list"){t.Fatal("missing capability navigation")};if strings.Contains(body,"implementation==='luca'")||strings.Contains(body,"implementation==='engo'"){t.Fatal("implementation-specific UI branch")}}

func TestWriteRequiresJSON(t *testing.T){r:=httptest.NewRequest("POST","/api/v1/bots/x/channels/join",strings.NewReader("{}"));w:=httptest.NewRecorder();testServer(t).Handler().ServeHTTP(w,r);if w.Code!=http.StatusForbidden{t.Fatalf("code=%d",w.Code)}}
func TestWriteRejectsCrossOrigin(t *testing.T){r:=httptest.NewRequest("POST","http://botweb.local/api/v1/bots/x/channels/join",strings.NewReader("{}"));r.Host="botweb.local";r.Header.Set("Content-Type","application/json");r.Header.Set("Origin","https://evil.example");w:=httptest.NewRecorder();testServer(t).Handler().ServeHTTP(w,r);if w.Code!=http.StatusForbidden{t.Fatalf("code=%d",w.Code)}}


func TestBotAIUIIsCapabilityDriven(t *testing.T){
	r:=httptest.NewRequest("GET","/app.js",nil);w:=httptest.NewRecorder();testServer(t).Handler().ServeHTTP(w,r);body:=w.Body.String()
	if !strings.Contains(body,"botai.status")||!strings.Contains(body,"/botai"){t.Fatal("missing BotAI capability view")}
	if strings.Contains(body,"implementation==='engo'"){t.Fatal("Engo-specific BotAI UI branch")}
}


func TestAuthViewerCanRead(t *testing.T){s:=testServer(t);s.auth=AuthConfig{ViewerToken:"view",OperatorToken:"operate"};r:=httptest.NewRequest("GET","/",nil);r.Header.Set("Authorization","Bearer view");w:=httptest.NewRecorder();s.Handler().ServeHTTP(w,r);if w.Code!=http.StatusOK{t.Fatalf("code=%d",w.Code)}}
func TestAuthRejectsMissingToken(t *testing.T){s:=testServer(t);s.auth=AuthConfig{ViewerToken:"view"};r:=httptest.NewRequest("GET","/api/v1/bots",nil);w:=httptest.NewRecorder();s.Handler().ServeHTTP(w,r);if w.Code!=http.StatusUnauthorized{t.Fatalf("code=%d",w.Code)}}
func TestViewerCannotWrite(t *testing.T){s:=testServer(t);s.auth=AuthConfig{ViewerToken:"view",OperatorToken:"operate"};r:=httptest.NewRequest("POST","/api/v1/bots/x/channels/join",strings.NewReader("{}"));r.Header.Set("Authorization","Bearer view");r.Header.Set("Content-Type","application/json");w:=httptest.NewRecorder();s.Handler().ServeHTTP(w,r);if w.Code!=http.StatusForbidden{t.Fatalf("code=%d",w.Code)}}
func TestHealthDoesNotRequireAuth(t *testing.T){s:=testServer(t);s.auth=AuthConfig{ViewerToken:"view"};r:=httptest.NewRequest("GET","/healthz",nil);w:=httptest.NewRecorder();s.Handler().ServeHTTP(w,r);if w.Code!=http.StatusOK{t.Fatalf("code=%d",w.Code)}}


func TestBrowserAuthRedirectsToLogin(t *testing.T){s:=testServer(t);s.auth=AuthConfig{ViewerToken:"view"};r:=httptest.NewRequest("GET","/",nil);w:=httptest.NewRecorder();s.Handler().ServeHTTP(w,r);if w.Code!=http.StatusSeeOther||w.Header().Get("Location")!="/login"{t.Fatalf("code=%d location=%q",w.Code,w.Header().Get("Location"))}}
func TestBrowserLoginCreatesSession(t *testing.T){s:=testServer(t);s.auth=AuthConfig{ViewerToken:"view"};r:=httptest.NewRequest("POST","/login",strings.NewReader("token=view"));r.Header.Set("Content-Type","application/x-www-form-urlencoded");w:=httptest.NewRecorder();s.Handler().ServeHTTP(w,r);if w.Code!=http.StatusSeeOther{t.Fatalf("code=%d",w.Code)};res:=w.Result();var ck *http.Cookie;for _,c:=range res.Cookies(){if c.Name=="botweb_session"{ck=c}};if ck==nil||!ck.HttpOnly||ck.SameSite!=http.SameSiteStrictMode{t.Fatal("missing hardened session cookie")};q:=httptest.NewRequest("GET","/",nil);q.AddCookie(ck);v:=httptest.NewRecorder();s.Handler().ServeHTTP(v,q);if v.Code!=http.StatusOK{t.Fatalf("session code=%d",v.Code)}}
func TestBrowserLoginRejectsBadToken(t *testing.T){s:=testServer(t);s.auth=AuthConfig{ViewerToken:"view"};r:=httptest.NewRequest("POST","/login",strings.NewReader("token=wrong"));r.Header.Set("Content-Type","application/x-www-form-urlencoded");w:=httptest.NewRecorder();s.Handler().ServeHTTP(w,r);if w.Code!=http.StatusUnauthorized{t.Fatalf("code=%d",w.Code)}}


func TestProxyHTTPSRequiresExplicitTrust(t *testing.T){r:=httptest.NewRequest("GET","http://botweb/",nil);r.Header.Set("X-Forwarded-Proto","https");if requestHTTPS(AuthConfig{},r){t.Fatal("untrusted forwarded proto accepted")};if !requestHTTPS(AuthConfig{TrustProxy:true},r){t.Fatal("trusted proxy https not accepted")}}
func TestSessionWriteRequiresCSRF(t *testing.T){s:=testServer(t);s.auth=AuthConfig{OperatorToken:"operate"};id,e:=s.sessions.create("operator");if e!=nil{t.Fatal(e)};r:=httptest.NewRequest("POST","/api/v1/bots/x/channels/join",strings.NewReader("{}"));r.Header.Set("Content-Type","application/json");r.AddCookie(&http.Cookie{Name:"botweb_session",Value:id});w:=httptest.NewRecorder();s.Handler().ServeHTTP(w,r);if w.Code!=http.StatusForbidden{t.Fatalf("code=%d",w.Code)}}
func TestBearerWriteDoesNotRequireCSRF(t *testing.T){s:=testServer(t);s.auth=AuthConfig{OperatorToken:"operate"};r:=httptest.NewRequest("POST","/api/v1/bots/x/channels/join",strings.NewReader("{}"));r.Header.Set("Content-Type","application/json");r.Header.Set("Authorization","Bearer operate");w:=httptest.NewRecorder();s.Handler().ServeHTTP(w,r);if w.Code==http.StatusForbidden{t.Fatalf("bearer request rejected as CSRF: %s",w.Body.String())}}


func TestSessionInfoDoesNotExposeSessionID(t *testing.T){s:=testServer(t);s.auth=AuthConfig{OperatorToken:"operate"};id,e:=s.sessions.create("operator");if e!=nil{t.Fatal(e)};r:=httptest.NewRequest("GET","/api/v1/session",nil);r.AddCookie(&http.Cookie{Name:"botweb_session",Value:id});w:=httptest.NewRecorder();s.Handler().ServeHTTP(w,r);if w.Code!=http.StatusOK{t.Fatalf("code=%d",w.Code)};if strings.Contains(w.Body.String(),id){t.Fatal("session ID exposed")};if !strings.Contains(w.Body.String(),"\"role\":\"operator\""){t.Fatal("role missing")}}
func TestSessionRotationInvalidatesOldID(t *testing.T){s:=testServer(t);id,e:=s.sessions.create("operator");if e!=nil{t.Fatal(e)};next,e:=s.sessions.rotate(id);if e!=nil{t.Fatal(e)};if next==id{t.Fatal("session ID not rotated")};if s.sessions.role(id)!=""{t.Fatal("old session still valid")};if s.sessions.role(next)!="operator"{t.Fatal("new session invalid")}}


func TestSessionInfoProvidesCSRFWithoutSessionID(t *testing.T){s:=testServer(t);s.auth=AuthConfig{OperatorToken:"operate"};id,e:=s.sessions.create("operator");if e!=nil{t.Fatal(e)};r:=httptest.NewRequest("GET","/api/v1/session",nil);r.AddCookie(&http.Cookie{Name:"botweb_session",Value:id});w:=httptest.NewRecorder();s.Handler().ServeHTTP(w,r);body:=w.Body.String();if !strings.Contains(body,"\"csrf_token\":"){t.Fatal("csrf token missing")};if strings.Contains(body,id){t.Fatal("session id exposed")}}


func TestAuthContextCarriesVerifiedIdentity(t *testing.T){s:=testServer(t);s.auth=AuthConfig{OperatorToken:"operate"};var role,method string;h:=authMiddleware(s.auth,s.sessions,http.HandlerFunc(func(w http.ResponseWriter,r *http.Request){role=authenticatedRole(r);method=authenticatedMethod(r);w.WriteHeader(http.StatusNoContent)}));r:=httptest.NewRequest("GET","/api/v1/bots",nil);r.Header.Set("Authorization","Bearer operate");w:=httptest.NewRecorder();h.ServeHTTP(w,r);if role!="operator"||method!="bearer"{t.Fatalf("role=%q method=%q",role,method)}}
func TestSessionAuthContextCarriesVerifiedIdentity(t *testing.T){s:=testServer(t);s.auth=AuthConfig{ViewerToken:"view"};id,e:=s.sessions.create("viewer");if e!=nil{t.Fatal(e)};var role,method string;h:=authMiddleware(s.auth,s.sessions,http.HandlerFunc(func(w http.ResponseWriter,r *http.Request){role=authenticatedRole(r);method=authenticatedMethod(r);w.WriteHeader(http.StatusNoContent)}));r:=httptest.NewRequest("GET","/api/v1/bots",nil);r.AddCookie(&http.Cookie{Name:"botweb_session",Value:id});w:=httptest.NewRecorder();h.ServeHTTP(w,r);if role!="viewer"||method!="session"{t.Fatalf("role=%q method=%q",role,method)}}


func TestAuditEventJSONSchema(t *testing.T){v:=auditEvent{Schema:"botweb.audit.v1",Event:"channels.join",Bot:"demo",Result:"ok",Auth:"bearer",Role:"operator"};b,e:=json.Marshal(v);if e!=nil{t.Fatal(e)};var got map[string]string;if e=json.Unmarshal(b,&got);e!=nil{t.Fatal(e)};if got["schema"]!="botweb.audit.v1"||got["event"]!="channels.join"||got["bot"]!="demo"||got["result"]!="ok"||got["auth"]!="bearer"||got["role"]!="operator"{t.Fatalf("unexpected audit event: %s",b)};for _,forbidden:=range []string{"token","cookie","csrf","payload","channel","module"}{if _,ok:=got[forbidden];ok{t.Fatalf("forbidden audit field %q",forbidden)}}}


func TestMetricsAreBoundedAndPrivacySafe(t *testing.T){s:=testServer(t);s.metrics.observe(true,10*time.Millisecond);s.metrics.observe(false,20*time.Millisecond);r:=httptest.NewRequest("GET","/metrics",nil);w:=httptest.NewRecorder();s.Handler().ServeHTTP(w,r);body:=w.Body.String();for _,want:=range []string{"botweb_registry_bots","botweb_pbmp_requests_total{result=\"ok\"} 1","botweb_pbmp_requests_total{result=\"error\"} 1","botweb_pbmp_request_duration_seconds_sum 0.030000"}{if !strings.Contains(body,want){t.Fatalf("missing %q in %s",want,body)}};for _,forbidden:=range []string{"channel=","module=","bot=","token=","session="}{if strings.Contains(body,forbidden){t.Fatalf("sensitive/high-cardinality metric label %q",forbidden)}}}


func TestReadyzFailsWhenConfiguredBotIsUnreachable(t *testing.T){s:=testServer(t);r:=httptest.NewRequest("GET","/readyz",nil);w:=httptest.NewRecorder();s.Handler().ServeHTTP(w,r);if w.Code!=http.StatusServiceUnavailable{t.Fatalf("status=%d body=%s",w.Code,w.Body.String())};if !strings.Contains(w.Body.String(),"\"reachable\":0"){t.Fatalf("body=%s",w.Body.String())}}
func TestReadyzEmptyRegistryIsReady(t *testing.T){p:=filepath.Join(t.TempDir(),"bots.json");if err:=os.WriteFile(p,[]byte(`{"bots":[]}`),0600);err!=nil{t.Fatal(err)};s,e:=New(p);if e!=nil{t.Fatal(e)};r:=httptest.NewRequest("GET","/readyz",nil);w:=httptest.NewRecorder();s.Handler().ServeHTTP(w,r);if w.Code!=http.StatusOK{t.Fatalf("status=%d body=%s",w.Code,w.Body.String())};if !strings.Contains(w.Body.String(),"\"ok\":true"){t.Fatalf("body=%s",w.Body.String())}}


func TestInvalidBearerDoesNotBypassSessionCSRF(t *testing.T){s:=testServer(t);s.auth=AuthConfig{OperatorToken:"op"};id,e:=s.sessions.create("operator");if e!=nil{t.Fatal(e)};r:=httptest.NewRequest("POST","/api/v1/bots/x/channels/join",strings.NewReader(`{"network":"n","name":"#c"}`));r.Header.Set("Content-Type","application/json");r.Header.Set("Authorization","Bearer invalid");r.AddCookie(&http.Cookie{Name:"botweb_session",Value:id});w:=httptest.NewRecorder();s.Handler().ServeHTTP(w,r);if w.Code!=http.StatusForbidden{t.Fatalf("status=%d",w.Code)}}
func TestInvalidBearerFallsBackToVerifiedSessionIdentity(t *testing.T){s:=newSessionStore();id,e:=s.create("viewer");if e!=nil{t.Fatal(e)};var gotRole,gotMethod string;h:=authMiddleware(AuthConfig{ViewerToken:"view"},s,http.HandlerFunc(func(_ http.ResponseWriter,r *http.Request){gotRole=authenticatedRole(r);gotMethod=authenticatedMethod(r)}));r:=httptest.NewRequest("GET","/",nil);r.Header.Set("Authorization","Bearer invalid");r.AddCookie(&http.Cookie{Name:"botweb_session",Value:id});h.ServeHTTP(httptest.NewRecorder(),r);if gotRole!="viewer"||gotMethod!="session"{t.Fatalf("role=%q method=%q",gotRole,gotMethod)}}
func TestViewerLogoutRequiresCSRF(t *testing.T){s:=testServer(t);s.auth=AuthConfig{ViewerToken:"view"};id,e:=s.sessions.create("viewer");if e!=nil{t.Fatal(e)};v,_:=s.sessions.get(id);r:=httptest.NewRequest("POST","/logout",nil);r.AddCookie(&http.Cookie{Name:"botweb_session",Value:id});w:=httptest.NewRecorder();s.Handler().ServeHTTP(w,r);if w.Code!=http.StatusForbidden{t.Fatalf("without csrf status=%d",w.Code)};r=httptest.NewRequest("POST","/logout",nil);r.AddCookie(&http.Cookie{Name:"botweb_session",Value:id});r.Header.Set("X-CSRF-Token",v.csrf);w=httptest.NewRecorder();s.Handler().ServeHTTP(w,r);if w.Code!=http.StatusSeeOther{t.Fatalf("with csrf status=%d",w.Code)}}
func TestTrustedProxyHTTPSOriginAccepted(t *testing.T){r:=httptest.NewRequest("POST","http://example.test/api",strings.NewReader("{}"));r.Host="example.test";r.Header.Set("Content-Type","application/json");r.Header.Set("Origin","https://example.test");r.Header.Set("X-Forwarded-Proto","https");if !validWriteRequest(AuthConfig{TrustProxy:true},r){t.Fatal("trusted proxy HTTPS origin rejected")}}


func TestSessionCreatePrunesExpired(t *testing.T){s:=newSessionStore();s.values["expired"]=session{role:"viewer",expires:time.Now().Add(-time.Minute)};if _,e:=s.create("viewer");e!=nil{t.Fatal(e)};s.mu.Lock();_,ok:=s.values["expired"];s.mu.Unlock();if ok{t.Fatal("expired session was not pruned")}}
func TestLoginReplacesExistingSession(t *testing.T){s:=testServer(t);s.auth=AuthConfig{ViewerToken:"view"};old,e:=s.sessions.create("viewer");if e!=nil{t.Fatal(e)};r:=httptest.NewRequest("POST","/login",strings.NewReader("token=view"));r.Header.Set("Content-Type","application/x-www-form-urlencoded");r.AddCookie(&http.Cookie{Name:"botweb_session",Value:old});w:=httptest.NewRecorder();s.Handler().ServeHTTP(w,r);if w.Code!=http.StatusSeeOther{t.Fatalf("status=%d body=%s",w.Code,w.Body.String())};if _,ok:=s.sessions.get(old);ok{t.Fatal("old session still valid after login")};res:=w.Result();defer res.Body.Close();var next string;for _,ck:=range res.Cookies(){if ck.Name=="botweb_session"{next=ck.Value}};if next==""||next==old{t.Fatal("replacement session cookie missing")};if _,ok:=s.sessions.get(next);!ok{t.Fatal("replacement session not valid")}}


func TestReadyzConcurrentProbeLatency(t *testing.T){endpoints:=[]string{"a","b","c"};start:=time.Now();reachable:=probeReachability(endpoints,func(string)bool{time.Sleep(100*time.Millisecond);return true});elapsed:=time.Since(start);if reachable!=3{t.Fatalf("reachable=%d",reachable)};if elapsed>=250*time.Millisecond{t.Fatalf("readiness probes appear sequential: %s",elapsed)};if elapsed<90*time.Millisecond{t.Fatalf("probe test did not exercise delay: %s",elapsed)}}

func TestReadyzUnauthenticatedWhenAuthEnabled(t *testing.T){s:=testServer(t);s.auth=AuthConfig{ViewerToken:"view",OperatorToken:"op"};r:=httptest.NewRequest("GET","/readyz",nil);w:=httptest.NewRecorder();s.Handler().ServeHTTP(w,r);if w.Code==http.StatusSeeOther||w.Code==http.StatusUnauthorized{t.Fatalf("readiness unexpectedly requires authentication: %d",w.Code)}}


func TestOperationalEndpointAuthContract(t *testing.T){s:=testServer(t);s.auth=AuthConfig{ViewerToken:"view",OperatorToken:"op"};for _,path:=range []string{"/healthz","/readyz"}{r:=httptest.NewRequest("GET",path,nil);w:=httptest.NewRecorder();s.Handler().ServeHTTP(w,r);if w.Code==http.StatusSeeOther||w.Code==http.StatusUnauthorized{t.Fatalf("%s unexpectedly requires authentication: %d",path,w.Code)}};r:=httptest.NewRequest("GET","/metrics",nil);w:=httptest.NewRecorder();s.Handler().ServeHTTP(w,r);if w.Code!=http.StatusSeeOther{t.Fatalf("metrics status=%d, want redirect to login",w.Code)}}


func TestBrowserLogoutUsesCSRFHeader(t *testing.T){if !strings.Contains(indexHTML,`id="logout"`){t.Fatal("logout button missing")};if strings.Contains(indexHTML,`action="/logout"`){t.Fatal("logout still uses plain form POST")};if !strings.Contains(js,`fetch('/logout'` )||!strings.Contains(js,`'X-CSRF-Token':session.csrf_token`){t.Fatal("browser logout does not send session CSRF token")}}


func TestLoginRejectsCrossOrigin(t *testing.T){s:=testServer(t);s.auth=AuthConfig{ViewerToken:"view"};r:=httptest.NewRequest("POST","http://botweb.local/login",strings.NewReader("token=view"));r.Host="botweb.local";r.Header.Set("Content-Type","application/x-www-form-urlencoded");r.Header.Set("Origin","https://evil.example");w:=httptest.NewRecorder();s.Handler().ServeHTTP(w,r);if w.Code!=http.StatusForbidden{t.Fatalf("status=%d",w.Code)}}
func TestLoginAcceptsTrustedProxyHTTPSOrigin(t *testing.T){s:=testServer(t);s.auth=AuthConfig{ViewerToken:"view",TrustProxy:true};r:=httptest.NewRequest("POST","http://botweb.local/login",strings.NewReader("token=view"));r.Host="botweb.local";r.Header.Set("Content-Type","application/x-www-form-urlencoded");r.Header.Set("Origin","https://botweb.local");r.Header.Set("X-Forwarded-Proto","https");w:=httptest.NewRecorder();s.Handler().ServeHTTP(w,r);if w.Code!=http.StatusSeeOther{t.Fatalf("status=%d body=%s",w.Code,w.Body.String())}}


func TestReadyzUsesPBMPRequiredInfoMethod(t *testing.T){if runtimeReadinessMethod!="pbmp.info"{t.Fatalf("readiness method=%q, want PBMP/1 M0 required method pbmp.info",runtimeReadinessMethod)}}


func TestReadinessUpdatesAggregateMetrics(t *testing.T){s:=testServer(t);r:=httptest.NewRequest("GET","/readyz",nil);w:=httptest.NewRecorder();s.Handler().ServeHTTP(w,r);if w.Code!=http.StatusServiceUnavailable{t.Fatalf("readyz status=%d",w.Code)};r=httptest.NewRequest("GET","/metrics",nil);w=httptest.NewRecorder();s.Handler().ServeHTTP(w,r);body:=w.Body.String();for _,want:=range []string{"botweb_bots_checked 1","botweb_bots_reachable 0"}{if !strings.Contains(body,want){t.Fatalf("missing %q in metrics: %s",want,body)}}}


func TestLoginRequiresFormContentType(t *testing.T){s:=testServer(t);s.auth=AuthConfig{ViewerToken:"view"};r:=httptest.NewRequest("POST","http://botweb.local/login",strings.NewReader("token=view"));r.Host="botweb.local";r.Header.Set("Content-Type","text/plain");w:=httptest.NewRecorder();s.Handler().ServeHTTP(w,r);if w.Code!=http.StatusUnsupportedMediaType{t.Fatalf("status=%d, want 415",w.Code)}}


func TestLoginIgnoresQueryCredentialField(t *testing.T){s:=testServer(t);s.auth=AuthConfig{ViewerToken:"body-value"};r:=httptest.NewRequest("POST","http://botweb.local/login?token=query-sentinel",strings.NewReader("token=body-value"));r.Host="botweb.local";r.Header.Set("Content-Type","application/x-www-form-urlencoded");w:=httptest.NewRecorder();s.Handler().ServeHTTP(w,r);if w.Code!=http.StatusSeeOther{t.Fatalf("status=%d, want 303",w.Code)}}


func TestSessionEndpointsAreNoStore(t *testing.T){s:=testServer(t);s.auth=AuthConfig{ViewerToken:"view",OperatorToken:"op"};cases:=[]struct{method,path,body,token string}{{"GET","/login","",""},{"POST","/login","token=view",""},{"GET","/api/v1/session","","view"}};for _,tc:=range cases{r:=httptest.NewRequest(tc.method,"http://botweb.local"+tc.path,strings.NewReader(tc.body));r.Host="botweb.local";if tc.body!=""{r.Header.Set("Content-Type","application/x-www-form-urlencoded")};if tc.token!=""{r.Header.Set("Authorization","Bearer "+tc.token)};w:=httptest.NewRecorder();s.Handler().ServeHTTP(w,r);if got:=w.Header().Get("Cache-Control");got!="no-store"{t.Fatalf("%s %s Cache-Control=%q",tc.method,tc.path,got)}}}


func TestLoginSessionCookieSecurityAttributes(t *testing.T){s:=testServer(t);s.auth=AuthConfig{ViewerToken:"view",TrustProxy:true};r:=httptest.NewRequest("POST","http://botweb.local/login",strings.NewReader("token=view"));r.Host="botweb.local";r.Header.Set("Content-Type","application/x-www-form-urlencoded");r.Header.Set("Origin","https://botweb.local");r.Header.Set("X-Forwarded-Proto","https");w:=httptest.NewRecorder();s.Handler().ServeHTTP(w,r);if w.Code!=http.StatusSeeOther{t.Fatalf("status=%d",w.Code)};cs:=w.Result().Cookies();if len(cs)!=1{t.Fatalf("cookies=%d",len(cs))};c:=cs[0];if c.Name!="botweb_session"||!c.HttpOnly||!c.Secure||c.SameSite!=http.SameSiteStrictMode||c.Path!="/"{t.Fatalf("unexpected session cookie: %#v",c)}}

func TestLogoutExpiresSessionCookie(t *testing.T){s:=testServer(t);s.auth=AuthConfig{ViewerToken:"view"};r:=httptest.NewRequest("POST","http://botweb.local/logout",nil);r.Host="botweb.local";r.Header.Set("Authorization","Bearer view");w:=httptest.NewRecorder();s.Handler().ServeHTTP(w,r);cs:=w.Result().Cookies();if len(cs)!=1{t.Fatalf("cookies=%d",len(cs))};c:=cs[0];if c.Name!="botweb_session"||c.MaxAge>=0||!c.HttpOnly||c.SameSite!=http.SameSiteStrictMode||c.Path!="/"{t.Fatalf("unexpected logout cookie: %#v",c)}}


func loginRequest(s *Server,token string)*httptest.ResponseRecorder{r:=httptest.NewRequest("POST","http://botweb.local/login",strings.NewReader("token="+token));r.Host="botweb.local";r.Header.Set("Content-Type","application/x-www-form-urlencoded");w:=httptest.NewRecorder();s.Handler().ServeHTTP(w,r);return w}
func TestLoginRateLimitAfterTenFailures(t *testing.T){s:=testServer(t);s.auth=AuthConfig{ViewerToken:"view"};for i:=0;i<10;i++{if w:=loginRequest(s,"bad");w.Code!=http.StatusUnauthorized{t.Fatalf("attempt %d status=%d",i+1,w.Code)}};if w:=loginRequest(s,"bad");w.Code!=http.StatusTooManyRequests{t.Fatalf("limited status=%d, want 429",w.Code)}}
func TestSuccessfulLoginClearsFailureLimiter(t *testing.T){s:=testServer(t);s.auth=AuthConfig{ViewerToken:"view"};for i:=0;i<9;i++{if w:=loginRequest(s,"bad");w.Code!=http.StatusUnauthorized{t.Fatalf("attempt %d status=%d",i+1,w.Code)}};if w:=loginRequest(s,"view");w.Code!=http.StatusSeeOther{t.Fatalf("success status=%d",w.Code)};for i:=0;i<9;i++{if w:=loginRequest(s,"bad");w.Code!=http.StatusUnauthorized{t.Fatalf("post-reset attempt %d status=%d",i+1,w.Code)}}}

func TestValidLoginAllowedAfterFailureLimit(t *testing.T){s:=testServer(t);s.auth=AuthConfig{ViewerToken:"view"};for i:=0;i<10;i++{if w:=loginRequest(s,"bad");w.Code!=http.StatusUnauthorized{t.Fatalf("attempt %d status=%d",i+1,w.Code)}};if w:=loginRequest(s,"bad");w.Code!=http.StatusTooManyRequests{t.Fatalf("limited bad login status=%d",w.Code)};if w:=loginRequest(s,"view");w.Code!=http.StatusSeeOther{t.Fatalf("valid login blocked by failure limiter: %d",w.Code)}}

func TestLoginRateLimitIncludesRetryAfter(t *testing.T){s:=testServer(t);s.auth=AuthConfig{ViewerToken:"view"};for i:=0;i<10;i++{loginRequest(s,"bad")};w:=loginRequest(s,"bad");if w.Code!=http.StatusTooManyRequests{t.Fatalf("status=%d",w.Code)};if got:=w.Header().Get("Retry-After");got!="60"{t.Fatalf("Retry-After=%q, want 60",got)}}

func TestLoginThrottleMetric(t *testing.T){s:=testServer(t);s.auth=AuthConfig{ViewerToken:"view"};for i:=0;i<10;i++{loginRequest(s,"bad")};if w:=loginRequest(s,"bad");w.Code!=http.StatusTooManyRequests{t.Fatalf("throttle status=%d",w.Code)};r:=httptest.NewRequest("GET","/metrics",nil);r.Header.Set("Authorization","Bearer view");w:=httptest.NewRecorder();s.Handler().ServeHTTP(w,r);if w.Code!=http.StatusOK{t.Fatalf("metrics status=%d",w.Code)};if !strings.Contains(w.Body.String(),"botweb_login_throttled_total 1\n"){t.Fatalf("missing throttle metric: %s",w.Body.String())}}

func TestLoginRejectsOversizedBody(t *testing.T){s:=testServer(t);s.auth=AuthConfig{ViewerToken:"view"};body:="token="+strings.Repeat("x",5000);r:=httptest.NewRequest("POST","http://botweb.local/login",strings.NewReader(body));r.Host="botweb.local";r.Header.Set("Content-Type","application/x-www-form-urlencoded");w:=httptest.NewRecorder();s.Handler().ServeHTTP(w,r);if w.Code!=http.StatusRequestEntityTooLarge{t.Fatalf("status=%d, want 413",w.Code)}}

func TestAPIResponsesAreNoStore(t *testing.T){s:=testServer(t);s.auth=AuthConfig{ViewerToken:"view"};r:=httptest.NewRequest("GET","/api/v1/bots",nil);r.Header.Set("Authorization","Bearer view");w:=httptest.NewRecorder();s.Handler().ServeHTTP(w,r);if w.Code!=http.StatusOK{t.Fatalf("status=%d",w.Code)};if got:=w.Header().Get("Cache-Control");got!="no-store"{t.Fatalf("Cache-Control=%q, want no-store",got)}}

func TestMediaTypeParsing(t *testing.T){for _,tc:=range []struct{ct,want string;ok bool}{{"application/json","application/json",true},{"application/json; charset=utf-8","application/json",true},{"application/jsonx","application/json",false},{"application/json; charset=","application/json",false},{"application/x-www-form-urlencoded; charset=UTF-8","application/x-www-form-urlencoded",true}}{r:=httptest.NewRequest("POST","/",nil);r.Header.Set("Content-Type",tc.ct);if got:=hasMediaType(r,tc.want);got!=tc.ok{t.Fatalf("Content-Type %q got %v want %v",tc.ct,got,tc.ok)}}}

func TestDecodeJSONBodyRejectsTrailingValue(t *testing.T){var v map[string]any;r:=httptest.NewRequest("POST","/",strings.NewReader("{\"id\":\"x\"}{\"id\":\"y\"}"));w:=httptest.NewRecorder();if e:=decodeJSONBody(w,r,&v);e==nil{t.Fatal("expected trailing JSON value to be rejected")}}
func TestDecodeJSONBodyAcceptsSingleValue(t *testing.T){var v map[string]any;r:=httptest.NewRequest("POST","/",strings.NewReader("{\"id\":\"x\"}\n"));w:=httptest.NewRecorder();if e:=decodeJSONBody(w,r,&v);e!=nil{t.Fatalf("single JSON value rejected: %v",e)};if v["id"]!="x"{t.Fatalf("id=%v",v["id"])}}

type strictJSONTestRequest struct{ID string `json:"id"`}
func TestDecodeJSONBodyRejectsUnknownField(t *testing.T){var v strictJSONTestRequest;r:=httptest.NewRequest("POST","/",strings.NewReader("{\"id\":\"x\",\"typo\":true}"));w:=httptest.NewRecorder();if e:=decodeJSONBody(w,r,&v);e==nil{t.Fatal("expected unknown JSON field to be rejected")}}

func TestJSONDecodeErrorReportsOversize(t *testing.T){var v strictJSONTestRequest;r:=httptest.NewRequest("POST","/",strings.NewReader("{\"id\":\""+strings.Repeat("x",5000)+"\"}"));w:=httptest.NewRecorder();e:=decodeJSONBody(w,r,&v);if e==nil{t.Fatal("expected oversized JSON error")};out:=httptest.NewRecorder();writeJSONDecodeError(out,e);if out.Code!=http.StatusRequestEntityTooLarge{t.Fatalf("status=%d, want 413",out.Code)}}

func TestDecodeJSONBodyRejectsEmptyBody(t *testing.T){var v strictJSONTestRequest;r:=httptest.NewRequest("POST","/",nil);w:=httptest.NewRecorder();e:=decodeJSONBody(w,r,&v);if e==nil{t.Fatal("expected empty JSON body to be rejected")};out:=httptest.NewRecorder();writeJSONDecodeError(out,e);if out.Code!=http.StatusBadRequest{t.Fatalf("status=%d, want 400",out.Code)}}

func TestChannelWriteRequiresNetworkAndName(t *testing.T){for _,body:=range []string{`{"network":"","name":"#test"}`,`{"network":"net","name":"   "}`}{s:=testServer(t);s.auth=AuthConfig{OperatorToken:"op"};r:=httptest.NewRequest("POST","/api/v1/bots/x/channels/join",strings.NewReader(body));r.Header.Set("Authorization","Bearer op");r.Header.Set("Content-Type","application/json");w:=httptest.NewRecorder();s.Handler().ServeHTTP(w,r);if w.Code!=http.StatusBadRequest{t.Fatalf("body=%s status=%d, want 400",body,w.Code)}}}

func TestModuleWriteRequiresID(t *testing.T){for _,body:=range []string{`{"id":""}`,`{"id":"   "}`}{s:=testServer(t);s.auth=AuthConfig{OperatorToken:"op"};r:=httptest.NewRequest("POST","/api/v1/bots/x/modules/reload",strings.NewReader(body));r.Header.Set("Authorization","Bearer op");r.Header.Set("Content-Type","application/json");w:=httptest.NewRecorder();s.Handler().ServeHTTP(w,r);if w.Code!=http.StatusBadRequest{t.Fatalf("body=%s status=%d, want 400",body,w.Code)}}}

func TestMethodNotAllowedIncludesAllow(t *testing.T){s:=testServer(t);for _,tc:=range []struct{method,path,allow string}{{"POST","/healthz","GET, HEAD"},{"PUT","/api/v1/bots","GET, HEAD"},{"GET","/logout","POST"}}{r:=httptest.NewRequest(tc.method,tc.path,nil);w:=httptest.NewRecorder();s.Handler().ServeHTTP(w,r);if w.Code!=http.StatusMethodNotAllowed{t.Fatalf("%s %s status=%d, want 405",tc.method,tc.path,w.Code)};if got:=w.Header().Get("Allow");got!=tc.allow{t.Fatalf("%s %s Allow=%q, want %q",tc.method,tc.path,got,tc.allow)}}}
