package server
import("encoding/json";"fmt";"log";"net/http";"strings";"sync";"time";"github.com/Ploos-AS/BotWeb/internal/pbmp";"github.com/Ploos-AS/BotWeb/internal/registry")
type metricsState struct{mu sync.Mutex;pbmpOK uint64;pbmpError uint64;pbmpNanos uint64}
func(m *metricsState)observe(ok bool,d time.Duration){m.mu.Lock();defer m.mu.Unlock();if ok{m.pbmpOK++}else{m.pbmpError++};m.pbmpNanos+=uint64(d)}
type Server struct{r registry.Registry;auth AuthConfig;sessions *sessionStore;metrics *metricsState}
func New(path string)(*Server,error){return NewWithAuth(path,AuthConfig{})}
func NewWithAuth(path string,auth AuthConfig)(*Server,error){r,e:=registry.Load(path);return &Server{r:r,auth:auth,sessions:newSessionStore(),metrics:&metricsState{}},e}
func(s *Server)Handler()http.Handler{m:=http.NewServeMux();m.HandleFunc("GET /",s.index);m.HandleFunc("GET /login",s.loginPage);m.HandleFunc("POST /login",s.login);m.HandleFunc("POST /logout",s.logout);m.HandleFunc("GET /app.css",assetCSS);m.HandleFunc("GET /api/v1/session",s.sessionInfo);m.HandleFunc("POST /api/v1/session/rotate",s.rotateSession);m.HandleFunc("GET /app.js",assetJS);m.HandleFunc("GET /metrics",s.metricsHandler);m.HandleFunc("GET /healthz",func(w http.ResponseWriter,_ *http.Request){w.Header().Set("Content-Type","application/json");w.Write([]byte("{\"ok\":true}\n"))});m.HandleFunc("GET /api/v1/bots",s.bots);m.HandleFunc("GET /api/v1/bots/",s.bot);m.HandleFunc("POST /api/v1/bots/",s.botAction);return securityHeaders(authMiddleware(s.auth,s.sessions,m))}
func securityHeaders(next http.Handler)http.Handler{return http.HandlerFunc(func(w http.ResponseWriter,r *http.Request){w.Header().Set("X-Content-Type-Options","nosniff");w.Header().Set("X-Frame-Options","DENY");w.Header().Set("Referrer-Policy","no-referrer");w.Header().Set("Content-Security-Policy","default-src 'self'; script-src 'self'; style-src 'self'; connect-src 'self'; img-src 'self'; base-uri 'none'; frame-ancestors 'none'");next.ServeHTTP(w,r)})}
func(s *Server)index(w http.ResponseWriter,r *http.Request){if r.URL.Path!="/"&&!strings.HasPrefix(r.URL.Path,"/bots/"){http.NotFound(w,r);return};w.Header().Set("Content-Type","text/html; charset=utf-8");w.Write([]byte(indexHTML))}
func(s *Server)bots(w http.ResponseWriter,_ *http.Request){type safe struct{ID string `json:"id"`;Name string `json:"name"`;Transport string `json:"transport"`};v:=make([]safe,0,len(s.r.Bots));for _,b:=range s.r.Bots{v=append(v,safe{b.ID,b.Name,b.Transport})};write(w,v)}
func(s *Server)bot(w http.ResponseWriter,r *http.Request){p:=strings.TrimPrefix(r.URL.Path,"/api/v1/bots/");parts:=strings.Split(strings.Trim(p,"/"),"/");if len(parts)!=2{http.NotFound(w,r);return};b,ok:=s.r.Find(parts[0]);if !ok||b.Transport!="unix"{http.NotFound(w,r);return};methods:=map[string]string{"info":"bot.info","capabilities":"capabilities.list","networks":"networks.list","protocol":"pbmp.info","channels":"channels.list","modules":"modules.list","metrics":"metrics.read","botai":"botai.status","logs":"logs.read","config":"config.read","config-schema":"config.schema"};method,ok:=methods[parts[1]];if !ok{http.NotFound(w,r);return};v,e:=s.pbmpCall(b.Endpoint,method,nil);if e!=nil{http.Error(w,e.Error(),http.StatusBadGateway);return};w.Header().Set("Content-Type","application/json");w.Write(v);w.Write([]byte("\n"))}
func validWriteRequest(r *http.Request)bool{ct:=r.Header.Get("Content-Type");if ct!="application/json"&&!strings.HasPrefix(ct,"application/json;"){return false};if o:=r.Header.Get("Origin");o!=""{prefix:="http://"+r.Host;if r.TLS!=nil{prefix="https://"+r.Host};if o!=prefix{return false}};return true}
type auditEvent struct{Schema string `json:"schema"`;Event string `json:"event"`;Bot string `json:"bot,omitempty"`;Result string `json:"result"`;Auth string `json:"auth,omitempty"`;Role string `json:"role,omitempty"`}
func audit(r *http.Request,event,bot,result string){v:=auditEvent{Schema:"botweb.audit.v1",Event:event,Bot:bot,Result:result,Auth:authenticatedMethod(r),Role:authenticatedRole(r)};b,e:=json.Marshal(v);if e!=nil{return};log.Print(string(b))}
func auditManagement(r *http.Request,event,bot,result string){audit(r,event,bot,result)}
func(s *Server)botAction(w http.ResponseWriter,r *http.Request){if !validWriteRequest(r){http.Error(w,"invalid write request",http.StatusForbidden);return};p:=strings.TrimPrefix(r.URL.Path,"/api/v1/bots/");parts:=strings.Split(strings.Trim(p,"/"),"/");if len(parts)!=3{http.NotFound(w,r);return}; if parts[1]=="modules"&&(parts[2]=="reload"||parts[2]=="enable"||parts[2]=="disable"){b,ok:=s.r.Find(parts[0]);if !ok||b.Transport!="unix"{http.NotFound(w,r);return};var q struct{ID string `json:"id"`};if json.NewDecoder(http.MaxBytesReader(w,r.Body,4096)).Decode(&q)!=nil||q.ID==""{http.Error(w,"invalid request",400);return};v,e:=s.pbmpCall(b.Endpoint,"modules."+parts[2],map[string]any{"id":q.ID});if e!=nil{auditManagement(r,"modules."+parts[2],parts[0],"error");http.Error(w,e.Error(),http.StatusBadGateway);return};auditManagement(r,"modules."+parts[2],parts[0],"ok");w.Header().Set("Content-Type","application/json");w.Write(v);w.Write([]byte("\n"));return}; if parts[1]!="channels"||(parts[2]!="join"&&parts[2]!="part"){http.NotFound(w,r);return};b,ok:=s.r.Find(parts[0]);if !ok||b.Transport!="unix"{http.NotFound(w,r);return};var q struct{Network string `json:"network"`;Name string `json:"name"`;Reason string `json:"reason"`};if json.NewDecoder(http.MaxBytesReader(w,r.Body,4096)).Decode(&q)!=nil{http.Error(w,"invalid request",400);return};method:="channels."+parts[2];v,e:=s.pbmpCall(b.Endpoint,method,map[string]any{"network":q.Network,"name":q.Name,"reason":q.Reason});if e!=nil{auditManagement(r,method,parts[0],"error");http.Error(w,e.Error(),http.StatusBadGateway);return};auditManagement(r,method,parts[0],"ok");w.Header().Set("Content-Type","application/json");w.Write(v);w.Write([]byte("\n"))}
func write(w http.ResponseWriter,v any){w.Header().Set("Content-Type","application/json");json.NewEncoder(w).Encode(v)}

func(s *Server)loginPage(w http.ResponseWriter,r *http.Request){if !s.auth.enabled(){http.Redirect(w,r,"/",http.StatusSeeOther);return};w.Header().Set("Content-Type","text/html; charset=utf-8");w.Write([]byte(loginHTML))}
func(s *Server)login(w http.ResponseWriter,r *http.Request){if !s.auth.enabled(){http.NotFound(w,r);return};if e:=r.ParseForm();e!=nil{http.Error(w,"invalid request",http.StatusBadRequest);return};role:=s.auth.role(r.FormValue("token"));if role==""{http.Error(w,"invalid credentials",http.StatusUnauthorized);return};id,e:=s.sessions.create(role);if e!=nil{http.Error(w,"session unavailable",http.StatusInternalServerError);return};http.SetCookie(w,&http.Cookie{Name:"botweb_session",Value:id,Path:"/",HttpOnly:true,Secure:requestHTTPS(s.auth,r),SameSite:http.SameSiteStrictMode,MaxAge:43200});http.Redirect(w,r,"/",http.StatusSeeOther)}
func(s *Server)logout(w http.ResponseWriter,r *http.Request){if ck,e:=r.Cookie("botweb_session");e==nil{s.sessions.delete(ck.Value);audit(r,"session.logout","","ok")};http.SetCookie(w,&http.Cookie{Name:"botweb_session",Value:"",Path:"/",HttpOnly:true,Secure:requestHTTPS(s.auth,r),SameSite:http.SameSiteStrictMode,MaxAge:-1});http.Redirect(w,r,"/login",http.StatusSeeOther)}

func(s *Server)sessionInfo(w http.ResponseWriter,r *http.Request){role:=requestRole(s.auth,s.sessions,r);out:=map[string]any{"authenticated":role!="","role":role};if ck,e:=r.Cookie("botweb_session");e==nil{if v,ok:=s.sessions.get(ck.Value);ok{out["created_at"]=v.created.UTC();out["expires_at"]=v.expires.UTC();out["csrf_token"]=v.csrf}};write(w,out)}
func(s *Server)rotateSession(w http.ResponseWriter,r *http.Request){ck,e:=r.Cookie("botweb_session");if e!=nil{http.Error(w,"session required",http.StatusBadRequest);return};id,e:=s.sessions.rotate(ck.Value);if e!=nil{http.Error(w,"session unavailable",http.StatusUnauthorized);return};http.SetCookie(w,&http.Cookie{Name:"botweb_session",Value:id,Path:"/",HttpOnly:true,Secure:requestHTTPS(s.auth,r),SameSite:http.SameSiteStrictMode,MaxAge:43200});audit(r,"session.rotate","","ok");w.WriteHeader(http.StatusNoContent)}

func(s *Server)metricsHandler(w http.ResponseWriter,_ *http.Request){s.metrics.mu.Lock();ok,fail,nanos:=s.metrics.pbmpOK,s.metrics.pbmpError,s.metrics.pbmpNanos;s.metrics.mu.Unlock();w.Header().Set("Content-Type","text/plain; version=0.0.4");fmt.Fprintf(w,"# HELP botweb_registry_bots Number of configured bots.\n# TYPE botweb_registry_bots gauge\nbotweb_registry_bots %d\n",len(s.r.Bots));fmt.Fprintf(w,"# HELP botweb_pbmp_requests_total PBMP requests by result.\n# TYPE botweb_pbmp_requests_total counter\nbotweb_pbmp_requests_total{result=\"ok\"} %d\nbotweb_pbmp_requests_total{result=\"error\"} %d\n",ok,fail);fmt.Fprintf(w,"# HELP botweb_pbmp_request_duration_seconds_sum Total PBMP request duration.\n# TYPE botweb_pbmp_request_duration_seconds_sum counter\nbotweb_pbmp_request_duration_seconds_sum %.6f\n",float64(nanos)/1e9)}
func(s *Server)pbmpCall(endpoint,method string,params map[string]any)(json.RawMessage,error){start:=time.Now();var v json.RawMessage;var e error;if params==nil{v,e=(pbmp.Client{Endpoint:endpoint}).Call(method)}else{v,e=(pbmp.Client{Endpoint:endpoint}).CallParams(method,params)};s.metrics.observe(e==nil,time.Since(start));return v,e}
